name: oxford3000

on:
    push:
        branches:
            - main

jobs:
    react-build:
        name: Build React.js Frontend
        runs-on: ubuntu-latest
        timeout-minutes: 5
        container: node:lts
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Compile React.js production build
              run: |
                  cd ./Frontend/oxford3000
                  npm i
                  npm run build
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: react-build-artifact
                  path: ./frontend/oxford3000/build
